# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SEWA Connect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SEWA Connect
  pod 'RxSwift', '~> 5'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'SEWA ConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SEWA ConnectUITests' do
    # Pods for testing
  end

end
